### ISSUE TITLE
Cant reduce Event duration

### ISSUE THREAD

**Issue by AdrianGzzEsc** [vkurko/calendar#46] opened 2022-06-21 20:29 UTC
After expanding the event its not possible to reduce it to one day, you can still expand it and short it but only into minimum 2 days

**Comment by vkurko** [comment] 2022-06-22 05:28
Hi @AdrianGzzEsc 

Thanks for reporting the issue. I can't reproduce it, but I can guess what you're facing. Could you please provide the exact start and end time of the event you are resizing?

**Comment by AdrianGzzEsc** [comment] 2022-06-22 05:31
The issue is also in the demo, try expanding an event and then reduce it to
one day and you cant. Im about to go to sleep but if you need more
information I’ll email you tomorrow

**Comment by vkurko** [comment] 2022-06-22 06:03
Ok. The point is that now in the month view, changes always occur in the form of plus or minus 1 day. Thus, if an event starts at 4pm and ends at 9am the next day, then it cannot be reduced by 1 day, because its duration is already less than 1 day.

The obvious solution would be to allow the end of the event to be reduced to, say, 5pm in this case, but in that case we will lose the original duration of the event as soon as we reduce it to the minimum value. That is, by reducing and then increasing the event, we will not get the original duration. I hope this makes sense.

What solution do you think would be the right one for such cases?

**Comment by AdrianGzzEsc** [comment] 2022-06-22 17:39
My bad, I see that it is working fine. It was just in does cases which
makes sense not being able to reduce it.

**Comment by vkurko** [comment] 2022-06-23 05:58
Yes, but anyway, I think the calendar behavior is really non-obvious in such cases.

I'll leave this ticket open, maybe there will be an idea how to improve the behavior. For example, FullCalendar seems to allow only all-day events to be resized in month view.

**Comment by AdrianGzzEsc** [comment] 2022-06-23 13:34
Maybe just grab the end date and subtract one day, so If it starts
2022-06-23 9:00am and ends  2022-06-24 5:30pm if you reduce it  to a one
day event then end date = 2022-06-23 5:30pm.
But the problem will be an event that ends before 24hrs for example:
starts 2022-06-23 9:00am and ends  2022-06-24 7:00am. Since you can drag
and change duration maybe just make it end at 23:59 if end date < start
date of the day and then user should change the time duration by drag in
it.

**Comment by vkurko** [comment] 2023-03-29 09:47
> I'll leave this ticket open, maybe there will be an idea how to improve the behavior. For example, FullCalendar seems to allow only all-day events to be resized in month view.

I'm closing this ticket for the time being with the possibility of reopening it if necessary.

**Closed by vkurko** 2023-03-29 09:47 UTC
