### ISSUE TITLE
 Event Slot Date

### ISSUE THREAD

**Issue by Rohit-webinventiv** [vkurko/calendar#53] opened 2022-08-03 09:44 UTC
I am facing issue in even slots, i.e. I have created the event between 13:00 to 14:00 but after saving the event, in calendar slots it get displayed between wrong time slots i.e. 01:00 to 02:00 which is wrong it should be displayed on the slots I have created while creating the event i.e. 13:00 to 14:00,
I have checked I have passed the correct value in start and end parameter.

Below is the code:
2022-08-03 13:00:00 to 2022-08-03 14:00:00

this.Events.forEach(event=> {
  let Event = {
          id: event.itemId,
          start: (event.FromTime),
          end: event.ToTime ? (event.ToTime) : '',
          resourceId: event.rId,
          title: event.title,
          color: event.color,
          extendedProps: event,
        }
 EventsPost.push(Event);
});

**Comment by vkurko** [comment] 2022-08-03 11:27
Hi @Rohit-webinventiv 

Could you prepare a [JS Bin](https://jsbin.com/) (or [JSFiddle](https://jsfiddle.net/), etc) example please, so that I can reproduce the problem?

Thanks

**Comment by Rohit-webinventiv** [comment] 2022-08-03 12:48
we are trying to integrate in angular

**Comment by vkurko** [comment] 2022-08-03 12:56
I'm sorry, but without being able to reproduce the issue, I won't be able to help you. The calendar seems to be fine, and the problem is probably in your third-party code.

**Comment by Rohit-webinventiv** [comment] 2022-08-03 13:50
can you suggest some of the point because of which I am facing these issue, So that I can troubleshoot those points.

**Comment by vkurko** [comment] 2022-08-03 17:30
Well, I would compare the actual events with the expected ones. You can get the actual events with the [getEvents()](https://github.com/vkurko/calendar#getevents) method.

**Comment by Rohit-webinventiv** [comment] 2022-08-04 06:57
Hello vkurko,
I am trying to create the demo, so that you can check but event calendar is not getting installed below is the link where I am trying to create demo.

https://stackblitz.com/edit/node-5hyjh3?file=angularcalendar%2Fsrc%2Fapp%2Fapp.component.html,angularcalendar%2Fsrc%2Fapp%2Fapp.component.ts

**Comment by vkurko** [comment] 2022-08-04 08:07
> event calendar is not getting installed

Maybe because this [package.json](https://stackblitz.com/edit/node-5hyjh3?file=angularcalendar%2Fsrc%2Fapp%2Fapp.component.html,package.json) is used and it is empty?

**Comment by Rohit-webinventiv** [comment] 2022-08-04 08:26
can you please check in angularcalendar1 directory there i have installed all the required modules, please check the code in app.component.ts file that i'm using in my app.

Package .json is not empty
{
  "name": "angularcalendar",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^14.1.0",
    "@angular/common": "^14.1.0",
    "@angular/compiler": "^14.1.0",
    "@angular/core": "^14.1.0",
    "@angular/forms": "^14.1.0",
    "@angular/platform-browser": "^14.1.0",
    "@angular/platform-browser-dynamic": "^14.1.0",
    "@angular/router": "^14.1.0",
    "@event-calendar/day-grid": "^0.11.2",
    "@event-calendar/list": "^0.11.2",
    "@event-calendar/resource-time-grid": "^0.11.2",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.1.1",
    "@angular/cli": "~14.1.1",
    "@angular/compiler-cli": "^14.1.0",
    "@event-calendar/core": "^0.11.2",
    "@event-calendar/time-grid": "^0.11.2",
    "@types/jasmine": "~4.0.0",
    "jasmine-core": "~4.2.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "typescript": "~4.7.2"
  }
}

**Comment by vkurko** [comment] 2022-08-04 09:42
I don't see anything strange in `app.component.ts`. I hope you'll manage to run the project so that we can reproduce the issue.

**Comment by Rohit-webinventiv** [comment] 2022-08-04 10:19
we are trying but the library is installed still getting error module not found can you please check

**Comment by vkurko** [comment] 2022-08-04 11:44
I think the project uses the [package.json](https://stackblitz.com/edit/node-5hyjh3?file=angularcalendar%2Fsrc%2Fapp%2Fapp.component.html,package.json) from the root directory, not yours. Maybe you need to move all your files out of the `angularcalendar` directory or you may want to try `cd angularcalendar && npm i && npm run start`. You'd better refer to the StackBlitz documentation.

As for the Event Calendar, I don't see any problem with how you initialize it.

**Comment by Rohit-webinventiv** [comment] 2022-08-05 10:12
Thanks for y help, I have updated the version of calendar after updation previous error get resolved.

**Comment by Rohit-webinventiv** [comment] 2022-08-05 10:14
But now eventClick: (eventClickInfo) => {

} function is not working

**Comment by vkurko** [comment] 2022-08-08 06:26
This was recently discussed in #52 and everything should work.

**Comment by vkurko** [comment] 2022-08-15 06:14
I hope I can close this issue.

**Closed by vkurko** 2022-08-15 06:14 UTC
