### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by lamorak13** [vkurko/calendar#95] opened 2023-03-23 16:16 UTC
Are there plans to also support typescript?

**Comment by vkurko** [comment] 2023-03-24 05:48
Yes, someday I will definitely add typescript support.  Unfortunately, I can't give an estimate right now.  Any help on this matter is welcome 😄

**Comment by ksmoore17** [comment] 2023-05-02 21:21
I have made progress on this. I switched the svelte packages to use svelte-package instead of rollup. I think this is a straight upgrade (as far as svelte support) from rollup, following svelte's/sveltekit's near-full migration to vite. In `common`, I have added some jsdoc and generated ambient types as well as manually created types for `Resource`, `Options`, `Duration`, `Plugin` and others. I tried to leave the internals mostly alone, but I made a few small changes like removing the `assign` utility function, for example (wasn't working nicely with typing). I also added a simple demo site for the svelte component.

I originally was planning on just forking and maintaining my own publication, so I have made some other changes like using pnpm with workspaces, removing rollup/publishing from the top level, adding a GitHub workflow, and adding a linter/formatter. However, I found I didn't really want to mess with the internals (common), so I ended up just doing as much jsdoc as I could on top of your source thinking maybe merging would be possible. I hope at least you can find some use in the typing that I have added if merging seems like a problem. Let me know if you would like me to make a pr. I took out the scripts for versioning and publishing because I wanted to do that with changesets but never got around to it (or changing it back).

I'd like to look into styling in the components instead of importing the scss stylesheet in `Calendar`. I think another improvement would be to migrate docs (especially the `Options` object) into jsdoc and generate from there.

Thank you for creating this package! You can see my fork here: [https://github.com/LeagueBrain/calendar]()

**Comment by vkurko** [comment] 2023-05-03 09:02
@ksmoore17 Thanks for starting this change. I looked at the result and it's impressive. I see value for the upstream repository in the types you defined [here](https://github.com/LeagueBrain/calendar/tree/types/packages/common/types).

I would not like to use jsdoc as an intermediate solution, but go straight to typescript. And I would not want to accept all your changes, because there are so many of them. Maybe the right way is a smooth transition to typescript by rewriting individual functions and components? So that no more than a few files get into the pull request at a time and for them it is possible to carefully do a code review?

**Comment by vkurko** [comment] 2023-05-03 18:58
- *GitHub workflow* - If it works as well as the current tool, then why not. Although it's not difficult for me to `npm run publish` when a new release is ready.
- *Workspaces* - I'm not sure I understand what it's about. Can you explain?
- *svelte-package* - It's from SvelteKit, right? I don't really see much point in using SvelteKit to develop the library. Maybe I don't know about some advantages that SvelteKit provides when working on a library, and not on a website. What will be the benefit?

More thoughts on typescript. Perhaps I was in a hurry with the fact that the entire project needs to be rewritten in typescript. After all, Svelte and SvelteKit projects that will use the Event Calendar will use the source files of the library. And if the project does not use typescript? It turns out an extra dependency that can limit the use of the library. I would like to avoid such a situation.

**Comment by kryptus36** [comment] 2023-06-19 02:19
Don't overthink this.

1. If you rewrite in typescript it doesn't force consumers of your lib to use it (the conversion to pure js will be done as part of your build/publish steps).
2. If you don't want to rewrite in TS simply supply the .d.ts files with your code

Option 2 is probably harder to maintain long term.

Great project! I hope you add ts sport soon.

**Comment by vkurko** [comment] 2023-06-19 07:15
> Don't overthink this.

Yeah, my concern was about Svelte/SvelteKit projects that use the library's source code. But after some research, I realized that it is possible to get pure JS Svelte source files as a result of compiling Typescript source code.

**Comment by erskingardner** [comment] 2023-12-14 16:12
Any updates on this?

**Comment by vkurko** [comment] 2023-12-14 16:54
Unfortunately, nothing was done on this task.

**Comment by ksmoore17** [comment] 2023-12-28 16:48
I'm sorry.. the fullcalendar model with the options object ended up not working for me, so I lost interest.

**Comment by Fernando-lamas** [comment] 2024-02-22 16:25
Is there an update on this? I am quite interested in using this

**Comment by syncsynchalt** [comment] 2024-08-16 21:38
See also issue #254, some users are exploring solutions for this issue but we can bring the conversation back here.

If anyone's interested in doing some early testing try putting [this file](https://github.com/user-attachments/files/16641939/EventCalendar.d.ts.txt) (rename from `.d.ts.txt` to `.d.ts`) in your project and let me know if any of the type descriptions seem erroneous.

**Comment by syncsynchalt** [comment] 2024-08-26 19:35
The community-supported type info is merged into the `@types` NPM repo and has been published, your IDE might auto-discover them or you may need to install them explicitly as dev dependencies.  For example in my project I added these as deps:

```
  "devDependencies": {
  ... snip ...
    "@types/event-calendar__core": "^3.4.0",
    "@types/event-calendar__interaction": "^3.4.0",
    "@types/event-calendar__resource-time-grid": "^3.4.0",
    "@types/event-calendar__time-grid": "^3.4.0",
  ... snip ...
```

If you spot any issues with the type info let me know or open a PR against the code at [the @types repo](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/event-calendar__core/) and it should automatically ping me for review.

**Comment by vkurko** [comment] 2024-08-26 21:17
@syncsynchalt Thank you very much for the work done. This is really impressive!

**Comment by syncsynchalt** [comment] 2024-10-04 22:08
FYI: I've added type hints for the two new 3.5+ features (`filterEventsWithResources` and `Resource.extendedProps`) in an additional PR to the community-maintained `@types/event-channel` package: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70792

Anyone can approve that PR if they're interested, but it won't be merged until someone on the typescript team looks.

If anyone would like to be a co-maintainer of the `@types` package let me know, that will allow us to mutually approve/review our changes without waiting for the TypeScript team to take a look.

**Comment by vkurko** [comment] 2024-10-07 11:24
> If anyone would like to be a co-maintainer of the `@types` package let me know

Please add me as a co-maintainer. Thank you.

**Comment by Flymeth** [comment] 2024-10-11 09:29
It seems like the "@types/event-calendar__core" lib does not export support for using calendar with svelte (and ts).
Is anyone having the same issue ?
![image](https://github.com/user-attachments/assets/535f18a8-e7e1-45d2-8c1c-7929f1dd8b1e)

**Comment by syncsynchalt** [comment] 2024-10-12 02:26
> It seems like the "@types/event-calendar__core" lib does not include support for using calendar with svelte (and ts). Is anyone having the same issue ?

That'll be for me to look into, I'll learn some Svelte and dig into this in the coming week.

I suspect I'll have to define `Calendar` as having props/methods similar to those listed [here](https://deno.land/x/svelte@v3.44.2/index.d.ts?s=SvelteComponentTyped), but I'll know better once I have a working (type-broken) example to play with.

**Comment by syncsynchalt** [comment] 2024-10-12 18:59
@Flymeth I'm unable to reproduce the error you're seeing, but I also had to add `plugins=` and `options=` attributes to `<Calendar />` (per the EC [readme](https://github.com/vkurko/calendar/?tab=readme-ov-file#javascript-module--svelte-component)) for it to render successfully.  `options` can be an empty object, but `plugins` must be an array of one or more plugins.

My test project is [here](https://github.com/syncsynchalt/svelte-event-calendar-demo), let me know if you can reproduce your error there or if you can give a sample project of your own and I'll take a look.

**Comment by Flymeth** [comment] 2024-10-12 19:11
![image](https://github.com/user-attachments/assets/f6a1f6d2-f7d5-4b9d-b95c-1a5e3cfd1035)
I just cloned your repo, and the typing issue is still here.
Apparently it's just a typing issue because i've no problem at build/dev time and the calendar is working on the web page.

I'll try to edit the package in node_modules to find out where the problem is coming from

**Comment by Flymeth** [comment] 2024-10-12 19:37
I just understood where the problem comes from (at least I hope) :
![image](https://github.com/user-attachments/assets/4b4cbad7-c85b-4946-aacc-3e902d86f9aa)
In your code you instanciate the SvelteComponent without any props (to be able to construct the calendar as a svelte component or as a class). But behind 

To type that it's very difficult (maybe impossible idk), so my solution was to better type the component and passing "options" as 'any'
![image](https://github.com/user-attachments/assets/2ba663cf-28b0-475f-804d-03dd9625f8bf)
The problem doing that is that I lost the "options" type when wanting to instanciate the calendar using the class.

I'll try to fin da solution tomorrow

**Comment by vkurko** [comment] 2024-11-29 14:26
Due to the appearance of the [@types](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/event-calendar__core/) repo , I think I can close this ticket. Please open a new one if necessary.

**Closed by vkurko** 2024-11-29 14:26 UTC
