### ISSUE TITLE
Incorrect class on the main calendar wrapper

### ISSUE THREAD

**Issue by ademaro** [vkurko/calendar#155] opened 2023-07-10 21:54 UTC
The "Day" view is selected, but the "Weeks" class is not removed from the markup.
![err](https://i.imgur.com/PxnU55R.png)

For Month or Week view, everything works as expected.

**Comment by vkurko** [comment] 2023-07-11 14:06
I will think about how to improve the css classes for different views.

**Comment by vkurko** [comment] 2023-08-24 08:47
I hope I can close this issue.

**Closed by vkurko** 2023-08-24 08:47 UTC
Labels: enhancement

**Comment by LeonHeidelbach** [comment] 2023-08-25 17:13
@vkurko Thank you for the very quick reply! Yes, I thought as much. When hardcoding one of the view's default css classes into the `theme.view` key the classes were set for every view.

In my opinion to improve the method of passing in theme overrides as an object would be to essentially just do a deep merge of the object the user sets in their options with your default values. At first I thought this was actually the way changing the theme was implemented, but after only supplying a few classes that I wanted to change, the entire calendar broke. However, if the option of supplying a function to the theme field would work for me, this would be fine as well.

A general way of improving the `theme.view` field in my opinion would be to just change it from being a string value into another dictionary, containing all of the different view default values. You could then just index into this object using the current view key in `options.view` and obtain the current class list. This way a user could just statically change the theme object without breaking the entire theming system.

I would imagine something like this:

```svelte
theme : {
  view : {
    dayGridMonth : 'ec-day-grid ec-month-view',
    listDay : 'ec-list ec-day-view',
    listMonth : 'ec-list ec-month-view',
    listWeek : 'ec-list ec-week-view',
    listYear : 'ec-list ec-year-view',
    resourceTimeGridDay : 'ec-time-grid ec-resource-day-view',
    resourceTimeGridWeek : 'ec-time-grid ec-resource-week-view',
    timeGridDay : 'ec-time-grid ec-day-view',
    timeGridWeek : 'ec-time-grid ec-week-view'
  }
}
```

Regarding the missing `weekdays` field, there has to be something wrong with the theme object which is supplied to the theme callback function. This is the code I use to setup the event calendar in my `+page.svelte`:

```svelte
<script>
  let plugins = [DayGrid, TimeGrid, List, Interaction];
  let options = {
    view: 'dayGridMonth',
    headerToolbar: {
	    start: 'prev,next today',
	    center: 'title',
	    end: 'dayGridMonth,timeGridWeek,timeGridDay,listMonth',
    },
    events: [
	    {
		    title: 'Test Event 1',
		    start: new Date(),
		    end: new Date(Date.now() + 60 * 60 * 1000),
	    },
    ],
    eventClick: (evt: any) => {
	    console.log(evt);
    },
    theme: (theme: CalendarThemeOptions) => {
	    theme.button = `ec-button dark:!bg-gray-800 dark:!text-white dark:hover:!bg-gray-700
		                hover:cursor-pointer`;
	    theme.icon = 'ec-icon dark:after:!border-white';
	    theme.today = 'ec-today dark:!bg-gray-600 dark:!text-white';
	    return theme;
    },
  };
</script>

<Calendar {plugins} {options} />
```

What I do then is simply trigger a page switch using sveltes `goto` function from `'$app/navigation'` to navigate to any other `+page.svelte`. When I then try to go back to the calendar page using the `goto` function, I get the described error. Maybe as an additional info, ssr is enabled for all pages in my app.

**Comment by vkurko** [comment] 2023-08-28 08:04
> I would imagine something like this:
> 
> ```svelte
> theme : {
>   view : {
>     dayGridMonth : 'ec-day-grid ec-month-view',
>     listDay : 'ec-list ec-day-view',
>     listMonth : 'ec-list ec-month-view',
>     listWeek : 'ec-list ec-week-view',
>     listYear : 'ec-list ec-year-view',
>     resourceTimeGridDay : 'ec-time-grid ec-resource-day-view',
>     resourceTimeGridWeek : 'ec-time-grid ec-resource-week-view',
>     timeGridDay : 'ec-time-grid ec-day-view',
>     timeGridWeek : 'ec-time-grid ec-week-view'
>   }
> }
> ```

I like this idea. I wonder why I didn't think of this before :smile:


> This leads me to believe that the error in version `2.3.0` has nothing to do with only a missing `weekdays` field but rather with some entirely corrupted store variable.

The `weekdays` field was added in v2.3.0. It seems that for version 2.3.0 you are passing the `theme` object from version 2.2.0, where this field did not exist yet.

I have not yet been able to reproduce the issue locally in SvelteKit.

**Comment by LeonHeidelbach** [comment] 2023-08-28 10:21
> > I would imagine something like this:
> > ```svelte
> > theme : {
> >   view : {
> >     dayGridMonth : 'ec-day-grid ec-month-view',
> >     listDay : 'ec-list ec-day-view',
> >     listMonth : 'ec-list ec-month-view',
> >     listWeek : 'ec-list ec-week-view',
> >     listYear : 'ec-list ec-year-view',
> >     resourceTimeGridDay : 'ec-time-grid ec-resource-day-view',
> >     resourceTimeGridWeek : 'ec-time-grid ec-resource-week-view',
> >     timeGridDay : 'ec-time-grid ec-day-view',
> >     timeGridWeek : 'ec-time-grid ec-week-view'
> >   }
> > }
> > ```
> 
> I like this idea. I wonder why I didn't think of this before 😄
> 

Great, implementing this would probably already fix my issues.

> > This leads me to believe that the error in version `2.3.0` has nothing to do with only a missing `weekdays` field but rather with some entirely corrupted store variable.
> 
> The `weekdays` field was added in v2.3.0. It seems that for version 2.3.0 you are passing the `theme` object from version 2.2.0, where this field did not exist yet.
> 
> I have not yet been able to reproduce the issue locally in SvelteKit.

@vkurko This error only occurs if I set a function (i.e. the one from my previous comment) to the `theme` variable and not when I set a static dictionary. So there is no way that I am passing the incorrect object. ;) The `weekdays` field does get properly set in the theme variable that is passed to the function and so does everything else (compared it to the default by console logging). From the debug output I can see that the error occurs in the module `@event-calendar/day-grid/src/Header.svelte` line 11, right here:

```svelte
import {
	SvelteComponentDev,
	action_destroyer,
	add_location,
	append_hydration_dev,
	attr_dev,
	children,
	claim_element,
	claim_space,
	component_subscribe, // <<= Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
	destroy_each,
	detach_dev,
	dispatch_dev,
	element,
	ensure_array_like_dev,
	init,
	insert_hydration_dev,
	is_function,
	noop,
	safe_not_equal,
	space,
	validate_slots,
	validate_store
} from "/node_modules/.vite/deps/svelte_internal.js?v=3021394d";
```
```console
Header.svelte:11 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at Object.hydrate [as h] (Header.svelte:11:46)
    at Object.create [as c] (stores.js:23:1)
    at Object.create [as c] (Header.svelte:10:15)
    at create_component (Component.js:33:17)
    at Object.create [as c] (View.svelte:29:7)
    at create_component (Component.js:33:17)
    at Object.create [as c] (Calendar.svelte:137:44)
    at create_component (Component.js:33:17)
    at Object.create [as c] (+page.svelte:126:34)
    at Object.create [as c] (Content.svelte:4:43)
```

Could it be that you are not properly unsubscribing from a store on destroying a component? I am just handwaving here, since I am not familiar with your code base but the issue is definitely related to stores, funnily enough only if `theme` is set to a function though.
