### ISSUE TITLE
How to make events run on specific time as well

### ISSUE THREAD

**Issue by AyushKumar2019** [vkurko/calendar#196] opened 2023-11-02 13:45 UTC
First of all Thanks @vkurko  for creating this Library, 
I am using this library to run events on the calendar with some logic  
so suppose the first event I run from 10th October 00:00 to 15th October 00:00 then the event will run from 10 to 15th October on the calendar ( all day: false View-DayGridMonth, plugin-[DayGrid, interaction]) 
If I changed the time from 00:00 to 00:01 or any other time the whole event would appear on the calendar for one more day 
that means now event could be seen running from 10th October 00:01 to 15th 00:001 (but it would appear on 16th October(full day) as well, but I need it to not show the timeline for the whole day but show the event on the calendar for particular hour, 
Can you suggest anything, how could I achieve this?
@vkurko 
@ademaro

**Comment by vkurko** [comment] 2023-11-02 15:15
I'm sorry I don't quite understand what the problem is. For an event not to be displayed on October 16, its end date should not be greater than `2023-10-16T00:00:00`. In `dayGrid` view, events are not displayed by hours. There are `timeGrid` views for this purpose. Can you clarify what result you would like to achieve?

**Comment by AyushKumar2019** [comment] 2023-11-02 17:26
Thanks for replying @vkurko 
what i am trying to achieve is -: 
![image](https://github.com/vkurko/calendar/assets/47534793/dfec4105-2062-4ff6-9d91-89db09d19404)

multiple events in day grid view but event could end in middle of the day ( or at any hour of the day) & another vent would start from that time 
![SampleGitHUB](https://github.com/vkurko/calendar/assets/47534793/3cde7a07-e3b4-495b-a0a0-1792c0b800e3)

**Comment by vkurko** [comment] 2023-11-03 06:59
Thanks for the clarification, but unfortunately this display of events in the month view is not supported.

**Comment by AyushKumar2019** [comment] 2023-11-03 17:08
@vkurko 
Thanks for replying, 
I am using this library to build something for my corporate project & need to deliver it soon, 
is it possible to add this feature?
as I couldn't switch to any other library at the last moment ( because I have written 100's of logic at the front end and back end using it)

**Comment by AyushKumar2019** [comment] 2023-11-03 17:19
@vkurko , 
is it possible to print the calender?
please suggest.

**Comment by vkurko** [comment] 2023-11-04 08:18
> is it possible to add this feature?

Only if you do it on your own :smile: I thought maybe you could get the desired result if you control the width of the events with your additional css classes.  In this case you could use the [eventClassNames](https://github.com/vkurko/calendar#eventclassnames) option and analyze the start and end dates of each event. Depending on the time value, set the appropriate css class that would shift the start and end of the event. Unfortunately I don't have a possibility to write such code for you, but I think you could try to do it.


> is it possible to print the calender?

At this point in the calendar nothing has been done to make it print _nicely_.

**Comment by vkurko** [comment] 2023-11-13 08:19
I hope I can close this issue.

**Closed by vkurko** 2023-11-13 08:19 UTC
